/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "Timer/Timer.h"

static volatile uint8_t digits[4] = {0,0,0,0};   /* current value */



Timer_Config Seg7_Timer;
GPIO_TypeDef *DIG_Port = GPIOD;
GPIO_TypeDef *SEG_PORT = GPIOA;

/*
 *        10     9     8     7     6
 *    _____|_____|_____|_____|_____|_____
 *   |                                   |
 *   |                                   |
 *   |       T                 U         |
 *   |                                   |
 *   |_____ _____ _____ _____ _____ _____|
 *         |     |     |     |     |
 *         1     2     3     4     5
 */

/*
 *  1 -> G
 *  2 -> DP
 *  3 -> A
 *  4 -> F
 *  5 -> DIG1
 *  6 -> D
 *  7 -> E
 *  8 -> C
 *  9 -> B
 *  10 -> DIG2
 */


uint8_t A = 0;
uint8_t B = 1;
uint8_t C = 2;
uint8_t D = 3;
uint8_t E = 4;
uint8_t F = 5;
uint8_t G = 6;
uint8_t DIG1 = 9;
uint8_t DIG2 = 10;
uint8_t DIG3 = 11;
uint8_t DIG4 = 12;

static const uint8_t seg_lut[10] = {
		/*0*/ 0b00111111,
		/*1*/ 0b00000110,
		/*2*/ 0b01011011,
		/*3*/ 0b01001111,
		/*4*/ 0b01100110,
		/*5*/ 0b01101101,
		/*6*/ 0b01111101,
		/*7*/ 0b00000111,
		/*8*/ 0b01111111,
		/*9*/ 0b01101111
};


void Select_DIG1(void)
{
	GPIO_Pin_Low(DIG_Port, DIG1);
}

void Select_DIG2(void)
{
	GPIO_Pin_Low(DIG_Port, DIG2);
}

void Diselect_DIG1(void)
{
	GPIO_Pin_High(DIG_Port, DIG1);
}

void Diselect_DIG2(void)
{
	GPIO_Pin_High(DIG_Port, DIG2);
}


void Select_DIG3(void)
{
	GPIO_Pin_Low(DIG_Port, DIG3);
}
void Diselect_DIG3(void)
{
	GPIO_Pin_High(DIG_Port, DIG3);
}

void Select_DIG4(void)
{
	GPIO_Pin_Low(DIG_Port, DIG4);
}
void Diselect_DIG4(void)
{
	GPIO_Pin_High(DIG_Port, DIG4);
}

void Seven_Segment_Display(void)
{

}
volatile   uint8_t mux_idx  = 0;


void Seg7_Update()
{
//	if(mux_idx)
//	{
//		Diselect_DIG1();
//		Select_DIG2();
//		SEG_PORT->ODR =  seg_lut[digits[0]];
//	}
//	else
//	{
//		Diselect_DIG2();
//		Select_DIG1();
//		SEG_PORT->ODR =  seg_lut[digits[1]];
//	}
//
//	mux_idx ^= 1;

	if(mux_idx == 0)
	{
		Diselect_DIG1();
		Diselect_DIG2();
		Diselect_DIG3();
		Select_DIG4();
		SEG_PORT->ODR =  seg_lut[digits[3]];
		mux_idx = 1;
	}
	else if(mux_idx == 1)
	{
		Diselect_DIG1();
		Diselect_DIG2();
		Diselect_DIG4();
		Select_DIG3();
		SEG_PORT->ODR =  seg_lut[digits[2]];
		mux_idx = 2;
	}
	else if(mux_idx == 2)
	{
		Diselect_DIG1();
		Diselect_DIG3();
		Diselect_DIG4();
		Select_DIG2();
		SEG_PORT->ODR =  seg_lut[digits[1]];
		mux_idx = 3;
	}
	else if(mux_idx == 3)
	{
		Diselect_DIG4();
		Diselect_DIG3();
		Diselect_DIG2();
		Select_DIG1();
		SEG_PORT->ODR =  seg_lut[digits[0]];
		mux_idx = 0;
	}

//	mux_idx ^= 1;

}


void Seg7_Init(TIM_TypeDef *update_Timer, GPIO_TypeDef *segIOPort, GPIO_TypeDef *digPort)
{
	GPIO_Pin_Init(segIOPort, A, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, B, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, C, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, D, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, E, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, F, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(segIOPort, G, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(digPort, DIG1, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Open_Drain, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.None, GPIO_Configuration.Alternate_Functions.None);
	GPIO_Pin_Init(digPort, DIG2, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Open_Drain, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.None, GPIO_Configuration.Alternate_Functions.None);


//	GPIO_Pin_Init(digPort, DIG1, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);
//	GPIO_Pin_Init(digPort, DIG2, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);


	Seg7_Timer.Port = update_Timer;
	Seg7_Timer.Mode = Timer_Configurations.Mode.Update;
	Seg7_Timer.Clock_Source = Timer_Configurations.Clock_Source.Internal;
	Seg7_Timer.DMA_Enable = false;
	Seg7_Timer.Direction = Timer_Configurations.Direction.Upcounting;
	Seg7_Timer.Interrupt_Request = Timer_Configurations.Interrupt_Request.Update_Interrupt;
	Seg7_Timer.ISR_Routines.Update_ISR = Seg7_Update;
	Seg7_Timer.Prescaler = (uint16_t)(8400)-1;
	Seg7_Timer.Autoreload_Value = 10000-1;
	Timer_Init(&Seg7_Timer);
	Timer_Trigger(&Seg7_Timer);
}

void display_number(uint8_t value)
{
	digits[0] = value / 1000;       /* thousands  */
	digits[1] = value / 100;       /* hundereds  */
	digits[0] = value / 10;       /* tens  */
	digits[1] = value % 1;       /* ones  */
}

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Seg7_Init(TIM6, SEG_PORT, DIG_Port);



	for(;;)
	{


		for(int n = 0; n < 100; n++)
		{

			display_number(n);

			Delay_milli(1000);
		}


	}
}
